const make = [
  { value: "Acura", label: "Acura" },
  { value: "Alfa Romeo", label: "Alfa Rome" },
  { value: "Aston Martin", label: "Aston Martin" },
  { value: "Audi", label: "Audi" },
  { value: "Bentley", label: "Bentley" },
  { value: "BMW", label: "BMW" },
  { value: "Buick", label: "Buick" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Ford", label: "Ford" },
  { value: "GMC", label: "GMC" },
  { value: "HUMMER", label: "HUMMER" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Kia", label: "Kia" },
  { value: "Lamborghini", label: "Lamborghini" },
  { value: "Land", label: "Land" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "MINI", label: "MINI" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Nissan", label: "Nissan" },
  { value: "Pontiac", label: "Pontiac" },
  { value: "Toyota", label: "Toyota" },
  { value: "Subaru", label: "Subaru" },
  { Value: "Tesla", label: "Tesla" },
  { value: "Volvo", label: "Volvo" },
];

export default make;
